//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordMenager.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordMenager.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data Source=Database.db.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;RSAParameters xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;D&gt;BDCCygMfN2IHnvFXu5Kc4RaLA18YaU8THhyyQvZsx3+OQrru6wFQlNPhR2trGoUZUOwoe0yM4UCwWT6JTGefQZ/+r2KV4grAUleB+GYmkyVqk9eK6xqbIS7W8ilB1EZ0XUiWjHJ+TWuVJyFTAkyRLRf/rN+U2CXMZrZxPzkWz9qFWivcsljtlJALJWaEsVQ4v9ZOMNUNH5FjVHkKaMCtFl7B0tDyu+Tvsai/ztifbmM+A2/ZNM+m/W0ixrjvSUSPBA62I2rV7aFmIzs7lHUhWXK89xCcPbkHGBpFeIdX83H14RiqnNdhyY/F/syQ4n6InOrH2k2tEnLpUGAPW4BbMSs2nGdLNTdssgqX [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;RSAParameters xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;Modulus&gt;7bhnZwuTgX7II61BJRdfdnO4nIFkfqrC3gwNOR1r7JHJ+2Nwzbz4t5/UZv9zdp/9yc1VNoghM/2x91SRKhhOS6L6UkpPfO09o1CGvU/JUcj4hXT5tzHsAVKzwRkLM0NM2k9PzM8uv3nPZWXEEoYzWLJfgCrvwoZwRAKmmlbkgNl6uR8ARKB0eO9P4/+Tzarn2o3b5wH8JcsBE879hB6NMrjlFh0oTfIqsBWaZZvgwBgGzMT2nY7qvVAPClpu3g3OC3cRGGAMg/OJVoYNrGAmscdZuPq/kztcO7QaVNlRhL7ohKoorHBKro8VoF+uOfEsbc0xO [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
    }
}
